- hosts: all
  sudo: yes
  sudo_user: root
  tasks:
    - name: copy nginx.conf
      template: src=nginx.conf dest=/etc/nginx/nginx.conf mode=644 owner=root group=root


    - name: restart nginx
      service: name=nginx state=restarted
